### ISSUE TITLE
Data is being wrongly displayed on some rasters visualizations (The scale int the raster zoom)

### ISSUE THREAD

**Issue by RodrigoEC** [OCA-UFCG/oca-frontend#115]
**Describe the bug**
To optimize the image display GEE's algorithm to merge a certain number of pixels into one, but on doing that it merges pixels with different values into a new one. E.g, if we merge two pixels of 2 and 0 value, GEE turns it into a one pixel with value 1, which displays different colors in the final image. We must find a work around for that. 

**To Reproduce**
1. Access `https://oca.lsd.ufcg.edu.br/map?name=veg&year=2000` and see that it has a lot of pink dot areas
2. Zoom in on any pink dot and you'll find out that it actually doesn't exists

**Expected behavior**
We want a way of merging these pixels and still optimize the loading time but without creating distinct new value. A good algorithm may be to transform these pixels into a new one that's equal to the more frequently one.

**Comment by LazaroQueiroz** [comment]
solved (apparently). just waiting further orientations.
